require 'pathname'
require 'yaml'
require './common/common'
require './common/jake'

chdir File.dirname(__FILE__)

load File.join(pwd, 'ui/rakefile')
load File.join(pwd, 'unit-tests/rakefile')

$rhostudioTemplate = ""

namespace "autotest" do

  task :config do
    puts 'start config'

    $ymlFile             = 'config.yml'
    $silentInstallerFlag = "/S"

    $config = Jake.config(File.open($ymlFile))
  end

  namespace "install" do

    task :rhostudio do
      startPathTo = $config["paths"]["rhostudio"]
      rmsTemplate = "RMS_*"
      pathTo      = getPathByTemplate(startPathTo, rmsTemplate)

      Jake.run(File.join(pathTo, $silentInstallerFlag))
    end

  end

  namespace "uninstall" do

    def runUnistall(pathToDir)
      uninstallNameTemplate = "uninstall*"
      unItems               = getPathByTemplate(pathToDir, uninstallNameTemplate)

      Jake.run(File.joun(unItems, $silentInstallerFlag))
    end

    task :rhostudio do      
      runUnistall getRhostudioSuitePath
    end

  end

  task :shutdown do
    Jake.run("shutdown /s /f /t 5")
  end

  task :run => ["autotest:config", "autotest:uninstall:rhostudio", "autotest:install:rhostudio", "autotest:ui:run"] do
  end

end